version: 2.0

jobs:
  build:
    docker:
      - image: typelead/eta:latest

    steps:
      - checkout

      - restore_cache:
          key: gradle-eta-v074-

      - run: ./gradlew pTML

      - run: etlas update

      - run:
          working-directory: ./tests/fatjar
          command: ./tests/fatjar/gradlew shadowJar

      - run:
          working-directory: ./tests/multi
          command: ./tests/multi/gradlew run

      - run:
          working-directory: ./tests/simple
          command: ./tests/simple/gradlew run

      - run:
          working-directory: ./tests/test
          command: ./tests/test/gradlew test

      - save_cache:
          key: gradle-eta-v074-{{ epoch }}
          paths:
            - "~/.etlas/config"
            - "~/.etlas/packages"
            - "~/.etlas/tools"
            - "~/.gradle/caches/transforms-1"
            - "~/.gradle/caches/modules-2"
            - "~/.gradle/caches/jars-3"
            - "~/.gradle/caches/4.7/genereated-gradle-jars"
            - "~/.gradle/wrapper"

workflows:
  version: 2
  full_cycle:
    jobs:
      - build
