version: 2.0

jobs:
  build:
    docker:
      - image: typelead/eta:latest

    steps:
      - checkout

      - restore_cache:
          key: gradle-eta-v073-

      - run: etlas update

      - run:
          command: ./gradlew shadowJar
          working-directory: tests/fatjar

      - run:
          command: ./gradlew run
          working-directory: tests/multi

      - run:
          command: ./gradlew run
          working-directory: tests/simple

      - run:
          command: ./gradlew test
          working-directory: tests/test

      - save_cache:
          key: gradle-eta-v073-{{ epoch }}
          paths:
            - "~/.etlas/config"
            - "~/.etlas/packages"
            - "~/.etlas/tools"

workflows:
  version: 2
  full_cycle:
    jobs:
      - build
